language: python
python:
  - '3.8'
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - secure: pyFRJ/HYfeXWHlXbAnTbYxVdUUsfwlM/O3N67zwbz5QlEck9XgkTeIHACk1NCPpsJ25Vw0Jxo8mhTgC4sBbNox6T5GG+RfSSwSBZJb6ee3V6d8sd3PlPguJzYgSeaDbCH0v2MF9vZL84LUy2+LSi+AlnCaMSxlqVEYgok08qDIdXtE8Oia8xnqzrQ/p0Ug4u2b8P17d5rz8bhuu+jrhCoE3dZpSchVYA6C6ftXrhXtp3hapF7anMcz3amxWKpjBYc+TzROgxs3uJoo0YO0i0SFvDTGRbs6SR/PD4yA/esCQXWkamkF3BOfZ0QLoDAQcCRDEVJTJYhDCtgxSP6EVFDFwQ4WQ7NagKw2dgl4hktkFkh50EzDegbAj8HG8s0pb1KaZd+/wli7ZILB9mQbZ8Mpruhtvv7TqWQ+wfylVAMTv4mOFo5ACGvru+E2mEpqAH2l4BocPtU5SOUvrI7dCmVHX0EL8lTEawYJpj2/cYfMz6C5G2IjkZrPCdt0EnTCcKZsHGNahQxUC28QuoBuQc+50JTl7ywsKqKr5naN6llF7eFLt/+6rcTQkVPtHuglqLjAkDIK0KBl+3T0O+SUM861zW7xxjhYL2h7okAT7CVVMe9HSXNg/I2dXob7kgmfjrIfYxNcf1nflYyr/5zBwo3jSlCRN5xmwawX4jadOpBIs=
before_install:
  - CLOUDSDK_PYTHON=python3.8
  - echo $super_secret_password | gpg --passphrase-fd 0 service-account.json.gpg
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - cat service-account.json
  - gcloud container clusters get-credentials multi-cluster --project multi-k8s-406513 --zone asia-east1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t will518/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true will518/react-test npm test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
