language: python
python:
  - '3.8'
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - secure: dGGfJNOd9acJufdLvekmpQSeQ04oxw3wgQoSFpIZdJGDShSsa+u2ekWHU9PwzgtLjsx8IHauXGQKRONenBPRIgTudn+lZnvqiME8R1u2glA2RwLnjJYZQwgOHQqsyzfvN3awq+zG1dSI79VO5chtEx6wSG+kbvhSxtv3ADqJYUIqa4a8Zzr8zKs/eqCRXOo3rPgdXrgmGDdBD2y6y0O9oy9zfMJqy+IblMTLQy9dL8F6NQLfr5L2KRMRQhIM571AjBeHGGFpt6XJ1Nu2DTYZ+IqOGuBYuzQAu5S5CFFxmDy5/WLtjrHdqNbuKTAPrTELb8GxqGouIokIEEJrxVPz7Qj0VJ8kgubwSsuWDjNpRXupFS44qhBVE7QnPU9rO1z7GfDjpNLWeAkFGrWGm/W3bFAnsF2IZC3NkSJ5zGLgLKvqRlzZWuc6OOl7p7oRIZ/ZUlFCEb/y7tkofqmp8SVpkluM5hwRlWIWeYxc/pFVUGra/xXPOkWxoZ3k9ILX8GvlcA7AwD124piEq/OL5jzFxazfkzUtgDd0hj2Hntn5VZyGGzfgOJChlx81eft+4j8i+SyaLw4UbhNuHsbUx4VfWQy8QpvMiQYM6FQ5g+Ml1cPtM/ONdoFWPCZyk5zwhYUgNNhE8cQhhaI3DAPX8MUHB81Moblz7MRBPXbC8ANTWj4=
before_install:
  - CLOUDSDK_PYTHON=python3.8
  - echo $super_secret_password | gpg --passphrase-fd 0 service-account.json.gpg
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - cat service-account.json
  - gcloud config set project multi-k8s-406513
  - gcloud config set compute/region asia-east1
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t will518/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true will518/react-test npm test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
